// ─────────────────────────────────────────────────────────────
// Karthikey AI — Agent Registry
// Fields:
//   id          unique slug used in routing /agents/[id]
//   dept        sidebar department filter
//   name        display name (must be unique)
//   desc        one-line description shown on card
//   icon        emoji icon
//   credits     credits consumed per run
//   badge       'Quick' | 'Adv' | 'Built'  (display tier)
//   inputType   'excel' | 'text' | 'crm' | 'call'
//   outputType  'table' | 'email' | 'report' | 'score' | 'plan' | 'draft'
//   keywords    semantic hints for NL search
//   nextAgents  suggested follow-up agent IDs (for feature: suggested next)
//   quickActions prompt shortcuts shown inside agent runner
// ─────────────────────────────────────────────────────────────

export const AGENTS = [

  // ── SALES ─────────────────────────────────────────────────
  {
    id: 'lead-qual',
    dept: 'Sales',
    name: 'Lead qualifier',
    desc: 'ICP scoring & smart routing of inbound leads',
    icon: '🎯',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['lead scoring', 'ICP', 'inbound', 'routing', 'qualify', 'rank leads', 'prioritise leads'],
    nextAgents: ['email-draft', 'pipeline', 'contact-enr'],
    quickActions: ['Score all leads', 'Who are my hottest leads?', 'Which leads to call first?', 'Summarise lead quality'],
  },
  {
    id: 'email-draft',
    dept: 'Sales',
    name: 'Email drafter',
    desc: 'Stage-aware personalised follow-up emails',
    icon: '✉️',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'email',
    keywords: ['email', 'follow up', 'outreach', 'personalised', 'cold email', 'sequence', 'reply'],
    nextAgents: ['pipeline', 'call-sum'],
    quickActions: ['Draft follow-up for hot leads', 'Write a re-engagement email', 'Best subject lines'],
  },
  {
    id: 'pipeline',
    dept: 'Sales',
    name: 'Pipeline manager',
    desc: 'Monitor deal health, flags stalls, prioritises wins',
    icon: '📊',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['pipeline', 'deal health', 'stalled deals', 'CRM', 'opportunities', 'funnel', 'win rate'],
    nextAgents: ['forecast', 'deal-coach', 'mgr-dash'],
    quickActions: ['Which deals are stalled?', 'Top 3 deals to focus on', 'Pipeline health summary'],
  },
  {
    id: 'forecast',
    dept: 'Sales',
    name: 'Forecast agent',
    desc: 'AI-driven quarterly revenue forecast with narrative',
    icon: '📈',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['forecast', 'revenue', 'quarterly', 'prediction', 'close rate', 'target', 'attainment'],
    nextAgents: ['mgr-dash', 'rev-fore'],
    quickActions: ['Forecast this quarter', 'What is my close rate?', 'Revenue at risk'],
  },
  {
    id: 'deal-coach',
    dept: 'Sales',
    name: 'Deal coach',
    desc: 'MEDDIC/SPIN next-action suggestions per opportunity',
    icon: '🧠',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'plan',
    keywords: ['deal coaching', 'MEDDIC', 'SPIN', 'next steps', 'objection handling', 'opportunity', 'strategy'],
    nextAgents: ['email-draft', 'proposal'],
    quickActions: ['Next steps for my top deal', 'Objection handling tips', 'What am I missing?'],
  },
  {
    id: 'mgr-dash',
    dept: 'Sales',
    name: 'Manager dashboard',
    desc: 'Weekly AI-narrated pipeline digest for managers',
    icon: '🗂️',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['manager', 'team digest', 'weekly report', 'rep performance', 'pipeline summary', 'leadership'],
    nextAgents: ['rep-coach', 'forecast'],
    quickActions: ['Weekly team digest', 'Rep performance summary', 'Top deals needing attention'],
  },
  {
    id: 'crm-hygiene',
    dept: 'Sales',
    name: 'CRM hygiene',
    desc: 'Nightly data quality audit with rep nudges',
    icon: '🧹',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['data quality', 'duplicates', 'missing fields', 'CRM cleanup', 'hygiene', 'audit', 'stale records'],
    nextAgents: ['data-qual', 'contact-enr'],
    quickActions: ['Find duplicate records', 'Missing fields report', 'Data quality score'],
  },
  {
    id: 'acct-res',
    dept: 'Sales',
    name: 'Account researcher',
    desc: 'Pre-call briefing: news, financials, tech stack',
    icon: '🔍',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['account research', 'pre-call', 'company news', 'financials', 'tech stack', 'briefing', 'intelligence'],
    nextAgents: ['email-draft', 'deal-coach', 'proposal'],
    quickActions: ['Research top accounts', 'Prepare call briefing', 'Find trigger events'],
  },
  {
    id: 'call-sum',
    dept: 'Sales',
    name: 'Call summariser',
    desc: 'Transcribes calls, extracts actions, logs to CRM',
    icon: '🎙️',
    credits: 2,
    badge: 'Adv',
    inputType: 'call',
    outputType: 'report',
    keywords: ['call summary', 'transcription', 'action items', 'meeting notes', 'CRM logging', 'follow up'],
    nextAgents: ['email-draft', 'deal-coach'],
    quickActions: ['Summarise call notes', 'Extract action items', 'Key commitments made'],
  },
  {
    id: 'proposal',
    dept: 'Sales',
    name: 'Proposal generator',
    desc: 'Auto-generates branded proposals from opportunity data',
    icon: '📄',
    credits: 3,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'draft',
    keywords: ['proposal', 'RFP', 'quote', 'document', 'branded', 'pitch deck', 'scope of work'],
    nextAgents: ['contract-an', 'quote-rev'],
    quickActions: ['Generate proposal', 'Executive summary', 'Pricing table draft'],
  },
  {
    id: 'comp-intel',
    dept: 'Sales',
    name: 'Competitive intel',
    desc: 'Battlecards & win/loss pattern analysis',
    icon: '⚔️',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['competitor', 'battlecard', 'win loss', 'competitive analysis', 'objections', 'differentiation'],
    nextAgents: ['deal-coach', 'email-draft'],
    quickActions: ['Competitor analysis', 'Win/loss patterns', 'Battlecard for top competitor'],
  },
  {
    id: 'contact-enr',
    dept: 'Sales',
    name: 'Contact enricher',
    desc: 'Fills missing contact fields from public sources',
    icon: '👤',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'table',
    keywords: ['enrich', 'contact data', 'LinkedIn', 'email validation', 'phone', 'missing fields', 'data append'],
    nextAgents: ['email-draft', 'lead-qual'],
    quickActions: ['Enrich missing fields', 'Find LinkedIn profiles', 'Validate email addresses'],
  },
  {
    id: 'onboard-coach',
    dept: 'Sales',
    name: 'Sales onboarding coach',
    desc: 'Interactive AI coach for new sales reps',
    icon: '🎓',
    credits: 1,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'plan',
    keywords: ['onboarding', 'new rep', 'sales training', 'playbook', 'ramp', 'product knowledge', 'coach'],
    nextAgents: ['rep-coach', 'train-rec'],
    quickActions: ['Playbook Q&A', 'Objection practice', 'Product knowledge quiz'],
  },
  {
    id: 'icp-builder',
    dept: 'Sales',
    name: 'ICP builder',
    desc: 'Builds your Ideal Customer Profile from closed-won data',
    icon: '🏆',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['ICP', 'ideal customer', 'target market', 'closed won', 'customer profile', 'segment', 'best fit'],
    nextAgents: ['lead-qual', 'seg-build'],
    quickActions: ['Build ICP from won deals', 'Segment by ICP fit', 'Routing recommendations'],
  },

  // ── SERVICE ───────────────────────────────────────────────
  {
    id: 'case-class',
    dept: 'Service',
    name: 'Case classifier',
    desc: 'Auto-categorises and prioritises inbound cases',
    icon: '📋',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'table',
    keywords: ['case classification', 'support ticket', 'priority', 'categorise', 'triage', 'helpdesk', 'routing'],
    nextAgents: ['response', 'esc-pred', 'sla-mon'],
    quickActions: ['Classify all cases', 'Which cases are urgent?', 'Assign priorities'],
  },
  {
    id: 'response',
    dept: 'Service',
    name: 'Response drafter',
    desc: 'Drafts empathetic, policy-compliant customer replies',
    icon: '💬',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'email',
    keywords: ['customer reply', 'support email', 'empathetic', 'policy', 'response', 'draft', 'ticket reply'],
    nextAgents: ['case-sum', 'sentiment'],
    quickActions: ['Draft reply for top case', 'Tone: empathetic & professional', 'Escalation response'],
  },
  {
    id: 'kb-agent',
    dept: 'Service',
    name: 'Knowledge base agent',
    desc: 'Surfaces relevant KB articles for open cases',
    icon: '📚',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'report',
    keywords: ['knowledge base', 'KB', 'articles', 'self service', 'FAQ', 'documentation', 'answer'],
    nextAgents: ['response', 'self-svc'],
    quickActions: ['Find relevant articles', 'Draft KB answer', 'Related case history'],
  },
  {
    id: 'esc-pred',
    dept: 'Service',
    name: 'Escalation predictor',
    desc: 'Flags cases at risk of escalation before they blow up',
    icon: '⚠️',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['escalation', 'risk', 'complaint', 'angry customer', 'flag', 'prevent', 'early warning'],
    nextAgents: ['response', 'churn-risk', 'agent-coach'],
    quickActions: ['Escalation risk score', 'At-risk cases now', 'Prevention actions'],
  },
  {
    id: 'sla-mon',
    dept: 'Service',
    name: 'SLA monitor',
    desc: 'Alerts agents when cases are approaching SLA breach',
    icon: '⏰',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['SLA', 'breach', 'deadline', 'overdue', 'response time', 'alert', 'service level'],
    nextAgents: ['esc-pred', 'case-class'],
    quickActions: ['Cases nearing SLA breach', 'Overdue cases', 'SLA performance report'],
  },
  {
    id: 'sentiment',
    dept: 'Service',
    name: 'Sentiment tracker',
    desc: 'Real-time sentiment scoring across open cases',
    icon: '😊',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['sentiment', 'NPS', 'customer mood', 'negative', 'positive', 'emotion', 'satisfaction'],
    nextAgents: ['churn-risk', 'csat-pred', 'response'],
    quickActions: ['Overall sentiment score', 'Most negative customers', 'Sentiment trends'],
  },
  {
    id: 'agent-coach',
    dept: 'Service',
    name: 'Agent coach',
    desc: 'Live suggestions to service agents during conversations',
    icon: '🎯',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'plan',
    keywords: ['coaching', 'live suggestions', 'agent support', 'difficult customer', 'upsell', 'script'],
    nextAgents: ['response', 'sentiment'],
    quickActions: ['Coaching tips for rep', 'Handle difficult customer', 'Upsell opportunities'],
  },
  {
    id: 'churn-risk',
    dept: 'Service',
    name: 'Churn risk detector',
    desc: 'Identifies customers likely to churn via CRM signals',
    icon: '🚨',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['churn', 'retention', 'at-risk', 'cancel', 'customer health', 'renewal', 'loyalty'],
    nextAgents: ['renewal', 'response', 'csat-pred'],
    quickActions: ['Churn risk scores', 'At-risk accounts', 'Retention actions'],
  },
  {
    id: 'case-sum',
    dept: 'Service',
    name: 'Case summariser',
    desc: 'Auto-summarises long case threads for handoffs',
    icon: '📝',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'report',
    keywords: ['case summary', 'handoff', 'thread', 'history', 'briefing', 'shift change', 'context'],
    nextAgents: ['response', 'kb-agent'],
    quickActions: ['Summarise all cases', 'Handoff briefing', 'Key open issues'],
  },
  {
    id: 'csat-pred',
    dept: 'Service',
    name: 'CSAT predictor',
    desc: 'Predicts satisfaction score before survey is sent',
    icon: '⭐',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['CSAT', 'satisfaction', 'survey', 'NPS', 'predict', 'score', 'customer experience'],
    nextAgents: ['sentiment', 'churn-risk'],
    quickActions: ['Predict CSAT scores', 'At-risk satisfaction', 'Improvement actions'],
  },
  {
    id: 'self-svc',
    dept: 'Service',
    name: 'Self-service bot',
    desc: 'Deflects common queries before agent routing',
    icon: '🤖',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'draft',
    keywords: ['self service', 'deflection', 'bot', 'automation', 'FAQ', 'chatbot', 'common queries'],
    nextAgents: ['kb-agent', 'case-class'],
    quickActions: ['Common query patterns', 'Deflection candidates', 'Bot script draft'],
  },

  // ── MARKETING ─────────────────────────────────────────────
  {
    id: 'camp-brief',
    dept: 'Marketing',
    name: 'Campaign brief writer',
    desc: 'Generates campaign briefs from audience & goal inputs',
    icon: '📣',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'draft',
    keywords: ['campaign brief', 'marketing plan', 'audience', 'goals', 'creative brief', 'strategy'],
    nextAgents: ['email-pers', 'seg-build', 'camp-anal'],
    quickActions: ['Write campaign brief', 'Target audience analysis', 'Campaign objectives'],
  },
  {
    id: 'seg-build',
    dept: 'Marketing',
    name: 'Segment builder',
    desc: 'Suggests audience segments from CRM data',
    icon: '🎯',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'table',
    keywords: ['segmentation', 'audience', 'cohort', 'persona', 'targeting', 'group', 'cluster'],
    nextAgents: ['email-pers', 'camp-brief', 'lead-mql'],
    quickActions: ['Build audience segments', 'High-value segments', 'Behavioural segments'],
  },
  {
    id: 'email-pers',
    dept: 'Marketing',
    name: 'Email personaliser',
    desc: 'Personalises bulk emails per contact at scale',
    icon: '📧',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'email',
    keywords: ['email personalisation', 'bulk email', 'mail merge', 'subject line', 'CTA', 'open rate'],
    nextAgents: ['camp-anal', 'lead-mql'],
    quickActions: ['Personalise email batch', 'Subject line variants', 'CTA optimisation'],
  },
  {
    id: 'lead-mql',
    dept: 'Marketing',
    name: 'MQL scoring agent',
    desc: 'Scores MQLs based on engagement + firmographic signals',
    icon: '📊',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['MQL', 'marketing qualified lead', 'scoring', 'engagement', 'firmographic', 'handoff to sales'],
    nextAgents: ['lead-qual', 'seg-build'],
    quickActions: ['Score MQL list', 'Engagement analysis', 'Ready-for-sales leads'],
  },
  {
    id: 'camp-anal',
    dept: 'Marketing',
    name: 'Campaign analyst',
    desc: 'Explains campaign performance & recommends next steps',
    icon: '📉',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['campaign analysis', 'performance', 'ROI', 'channel', 'attribution', 'conversion', 'spend'],
    nextAgents: ['camp-brief', 'content-gap'],
    quickActions: ['Analyse my campaigns', 'Best performing channel', 'Where to spend more?'],
  },
  {
    id: 'content-gap',
    dept: 'Marketing',
    name: 'Content gap finder',
    desc: 'Identifies missing content for buyer journey stages',
    icon: '🔎',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['content gap', 'buyer journey', 'funnel', 'SEO', 'content calendar', 'missing content', 'awareness'],
    nextAgents: ['camp-brief', 'abm-res'],
    quickActions: ['Map content gaps', 'Missing funnel stages', 'Content calendar ideas'],
  },
  {
    id: 'abm-res',
    dept: 'Marketing',
    name: 'ABM researcher',
    desc: 'Deep-researches target accounts for ABM plays',
    icon: '🏢',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['ABM', 'account based marketing', 'target accounts', 'personalised', 'enterprise', 'research'],
    nextAgents: ['camp-brief', 'email-pers', 'acct-res'],
    quickActions: ['ABM target research', 'Account intelligence', 'Personalised outreach'],
  },
  {
    id: 'social-list',
    dept: 'Marketing',
    name: 'Social listening agent',
    desc: 'Monitors brand mentions & surfaces CRM contacts',
    icon: '📱',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['social media', 'brand mention', 'listening', 'Twitter', 'LinkedIn', 'sentiment', 'influencer'],
    nextAgents: ['sentiment', 'camp-brief'],
    quickActions: ['Brand mention analysis', 'Social sentiment', 'Influencer identification'],
  },
  {
    id: 'event-follow',
    dept: 'Marketing',
    name: 'Event follow-up agent',
    desc: 'Auto-creates follow-up sequences post-event',
    icon: '🎪',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'email',
    keywords: ['event', 'follow up', 'sequence', 'attendees', 'webinar', 'conference', 'post-event'],
    nextAgents: ['email-pers', 'lead-qual'],
    quickActions: ['Post-event follow-up sequence', 'Attendee prioritisation', 'Email sequences'],
  },

  // ── OPERATIONS ────────────────────────────────────────────
  {
    id: 'data-qual',
    dept: 'Ops',
    name: 'Data quality auditor',
    desc: 'Detects duplicates, stale records, missing fields',
    icon: '🔧',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['data quality', 'duplicates', 'stale', 'missing', 'audit', 'clean', 'governance'],
    nextAgents: ['crm-hygiene', 'contact-enr', 'intg-mon'],
    quickActions: ['Full data audit', 'Duplicate detection', 'Missing field report'],
  },
  {
    id: 'intg-mon',
    dept: 'Ops',
    name: 'Integration monitor',
    desc: 'Watches API sync health and alerts on failures',
    icon: '🔗',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'report',
    keywords: ['integration', 'API', 'sync', 'failure', 'health check', 'connector', 'middleware'],
    nextAgents: ['data-qual', 'sec-audit'],
    quickActions: ['Check sync status', 'Recent failures', 'Data freshness report'],
  },
  {
    id: 'rel-notes',
    dept: 'Ops',
    name: 'Release notes agent',
    desc: 'Summarises CRM updates and flags config impacts',
    icon: '📋',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'report',
    keywords: ['release notes', 'CRM update', 'configuration', 'impact', 'change management', 'version'],
    nextAgents: ['user-adopt', 'sec-audit'],
    quickActions: ['Latest CRM updates', 'Impact on my config', 'Action items from release'],
  },
  {
    id: 'user-adopt',
    dept: 'Ops',
    name: 'User adoption tracker',
    desc: 'Flags low-adoption users and suggests training',
    icon: '👥',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['adoption', 'usage', 'training', 'engagement', 'login', 'inactive users', 'CRM usage'],
    nextAgents: ['train-rec', 'rep-coach'],
    quickActions: ['Adoption report', 'Low-engagement users', 'Training recommendations'],
  },
  {
    id: 'wf-builder',
    dept: 'Ops',
    name: 'Workflow builder',
    desc: 'Drafts automation flows from plain-language prompts',
    icon: '⚡',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'plan',
    keywords: ['workflow', 'automation', 'flow builder', 'trigger', 'action', 'process', 'no-code'],
    nextAgents: ['intg-mon', 'data-qual'],
    quickActions: ['Design automation flow', 'Trigger & action setup', 'Flow optimisation'],
  },
  {
    id: 'sec-audit',
    dept: 'Ops',
    name: 'Security audit agent',
    desc: 'Reviews field-level security and sharing rules',
    icon: '🔒',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['security', 'field level', 'sharing rules', 'permissions', 'access control', 'compliance', 'audit'],
    nextAgents: ['intg-mon', 'data-qual'],
    quickActions: ['Security audit report', 'Sharing rule review', 'Risk assessment'],
  },
  {
    id: 'report-gen',
    dept: 'Ops',
    name: 'Report generator',
    desc: 'Turns plain-language questions into CRM reports',
    icon: '📊',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['report', 'dashboard', 'KPI', 'metrics', 'analytics', 'plain language', 'query'],
    nextAgents: ['mgr-dash', 'forecast'],
    quickActions: ['Generate pipeline report', 'Custom dashboard', 'KPI summary'],
  },

  // ── FINANCE ───────────────────────────────────────────────
  {
    id: 'quote-rev',
    dept: 'Finance',
    name: 'Quote reviewer',
    desc: 'Flags errors, discount violations, missing terms',
    icon: '🧾',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['quote', 'discount', 'pricing', 'approval', 'terms', 'error', 'CPQ', 'review'],
    nextAgents: ['proposal', 'contract-an', 'commission'],
    quickActions: ['Review all quotes', 'Discount violations?', 'Missing required fields'],
  },
  {
    id: 'commission',
    dept: 'Finance',
    name: 'Commission calculator',
    desc: 'Calculates rep commissions from closed opportunity data',
    icon: '💰',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'table',
    keywords: ['commission', 'compensation', 'incentive', 'closed deals', 'payout', 'variable pay', 'earnings'],
    nextAgents: ['rep-coach', 'mgr-dash'],
    quickActions: ['Calculate commissions', 'Top earners this month', 'Commission disputes'],
  },
  {
    id: 'renewal',
    dept: 'Finance',
    name: 'Renewal risk agent',
    desc: 'Flags accounts at renewal risk 90 days early',
    icon: '🔄',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'score',
    keywords: ['renewal', 'subscription', '90 days', 'contract end', 'churn', 'at-risk', 'retention'],
    nextAgents: ['churn-risk', 'response', 'contract-an'],
    quickActions: ['90-day renewal risk', 'At-risk accounts', 'Renewal action plan'],
  },
  {
    id: 'contract-an',
    dept: 'Finance',
    name: 'Contract analyser',
    desc: 'Extracts key terms from contracts and logs to CRM',
    icon: '📜',
    credits: 2,
    badge: 'Adv',
    inputType: 'text',
    outputType: 'report',
    keywords: ['contract', 'terms', 'legal', 'expiry', 'obligations', 'extract', 'clause', 'SLA terms'],
    nextAgents: ['renewal', 'quote-rev'],
    quickActions: ['Extract contract terms', 'Expiry dates summary', 'Key obligations'],
  },
  {
    id: 'rev-fore',
    dept: 'Finance',
    name: 'Revenue forecaster',
    desc: 'Bottoms-up revenue forecast with confidence intervals',
    icon: '📈',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['revenue forecast', 'bottoms up', 'confidence interval', 'ARR', 'MRR', 'growth', 'projection'],
    nextAgents: ['forecast', 'mgr-dash'],
    quickActions: ['Revenue forecast', 'Confidence intervals', 'Segment breakdown'],
  },
  {
    id: 'inv-rec',
    dept: 'Finance',
    name: 'Invoice reconciler',
    desc: 'Matches CRM closed-won deals to invoice records',
    icon: '🔢',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'table',
    keywords: ['invoice', 'reconciliation', 'closed won', 'billing', 'payment', 'match', 'exception'],
    nextAgents: ['quote-rev', 'commission'],
    quickActions: ['Match deals to invoices', 'Unreconciled items', 'Invoice exceptions'],
  },

  // ── HR ────────────────────────────────────────────────────
  {
    id: 'rep-coach',
    dept: 'HR',
    name: 'Rep performance coach',
    desc: 'Weekly individual feedback from CRM activity data',
    icon: '🏅',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['performance', 'coaching', 'feedback', 'rep', 'individual', 'activity', 'improvement'],
    nextAgents: ['train-rec', 'skills-gap', 'onboard-coach'],
    quickActions: ['Coach report for my team', 'Top performer analysis', 'Who needs support?'],
  },
  {
    id: 'onboard-guide',
    dept: 'HR',
    name: 'Onboarding guide',
    desc: 'Personalised onboarding checklist for new hires',
    icon: '🗺️',
    credits: 1,
    badge: 'Quick',
    inputType: 'text',
    outputType: 'plan',
    keywords: ['onboarding', 'new hire', 'checklist', '30 60 90', 'ramp', 'induction', 'first week'],
    nextAgents: ['onboard-coach', 'train-rec'],
    quickActions: ['New hire checklist', '30-60-90 day plan', 'Ramp progress check'],
  },
  {
    id: 'train-rec',
    dept: 'HR',
    name: 'Training recommender',
    desc: 'Suggests training based on deal loss patterns',
    icon: '📖',
    credits: 1,
    badge: 'Quick',
    inputType: 'excel',
    outputType: 'plan',
    keywords: ['training', 'learning', 'skill', 'deal loss', 'gap', 'L&D', 'development', 'course'],
    nextAgents: ['skills-gap', 'rep-coach'],
    quickActions: ['Training recommendations', 'Skill gaps from losses', 'Learning plan'],
  },
  {
    id: 'skills-gap',
    dept: 'HR',
    name: 'Skills gap analyser',
    desc: 'Identifies skill gaps from call & activity data',
    icon: '🎯',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['skills gap', 'capability', 'competency', 'call data', 'activity', 'team development'],
    nextAgents: ['train-rec', 'rep-coach'],
    quickActions: ['Skills gap analysis', 'Team capability map', 'Development priorities'],
  },
  {
    id: 'territory',
    dept: 'HR',
    name: 'Territory analyser',
    desc: 'Evaluates territory fairness, recommends realignment',
    icon: '🗺️',
    credits: 2,
    badge: 'Adv',
    inputType: 'excel',
    outputType: 'report',
    keywords: ['territory', 'alignment', 'fairness', 'coverage', 'region', 'quota', 'rebalance'],
    nextAgents: ['mgr-dash', 'rep-coach'],
    quickActions: ['Territory balance report', 'Rebalancing recommendations', 'Coverage gaps'],
  },
]

export const DEPTS = ['All', 'Sales', 'Service', 'Marketing', 'Ops', 'Finance', 'HR']

export const CREDIT_PACKS = [
  { id: 'trial',      name: 'Trial',     credits: 5,    price: 0,      priceInr: '₹0',     description: 'Try any 5 agents free' },
  { id: 'starter',    name: 'Starter',   credits: 25,   price: 49900,  priceInr: '₹499',   description: 'Best for individuals' },
  { id: 'growth',     name: 'Growth',    credits: 100,  price: 149900, priceInr: '₹1,499', description: 'Most popular' },
  { id: 'business',   name: 'Business',  credits: 300,  price: 349900, priceInr: '₹3,499', description: 'For growing teams' },
  { id: 'enterprise', name: 'Enterprise',credits: 1000, price: 999900, priceInr: '₹9,999', description: 'Agencies & large orgs' },
]
